# This config file is for RecipeSage-selfhost config version 2026-08-16, and RecipeSage version 4.0.3.

x-common-env: &common-env
  # === THESE VALUES MUST BE CHANGED ===
  #
  API_PUBLIC_BASE_URL: https://example.com/api # Change "example.com" to the domain used for RecipeSage. Do not remove the "/api" suffix.


  # === THESE VALUES MAY OPTIONALLY BE CHANGED, BUT DO NOT NEED TO BE ===
  #
  GRIP_KEY: recipesage_selfhost # Pushpin is only exposed within the docker network, so you can leave this as-is if desired.
  POSTGRES_DB: recipesage_selfhost # If changing this, make sure to update the DATABASE_URL below accordingly
  POSTGRES_USER: recipesage_selfhost # If changing this, make sure to update the DATABASE_URL below accordingly
  POSTGRES_PASSWORD: recipesage_selfhost # If changing this, make sure to update the DATABASE_URL below accordingly
  DATABASE_URL: postgresql://recipesage_selfhost:recipesage_selfhost@postgres:5432/recipesage_selfhost # Format is: postgresql://USERNAME:PASSWORD@HOST:PORT/DBNAME and must match the variables above
  GROCERY_CATEGORIZER_URL: https://grocery-categorizer.recipesage.com/ # If you would like to run this service locally rather than being dependent on RecipeSage cloud, please uncomment the corresponding service at the bottom of this file.
  AI_PROVIDER: "openrouter" # Please follow the instructions in the README if you decide to supply a value here (openrouter specified by default since all model names are specified in openrouter format)
  AI_API_KEY: "" # Please follow the instructions in the README if you decide to supply a value here
  AI_API_BASE_URL: "" # This does not need to be changed unless you are self-hosting your own LLM. Please follow the instructions in the README if you decide to supply a value here
  AI_MODEL_WEBPAGE: google/gemini-2.5-flash-lite # This model is recommended for this purpose
  AI_MODEL_TEXT: google/gemini-2.5-flash-lite # This model is recommended for this purpose
  AI_MODEL_OCR: google/gemini-2.5-flash # This model is recommended for this purpose
  AI_MODEL_DOCUMENT: google/gemini-2.5-flash # This model is recommended for this purpose
  AI_MODEL_MODERATION: google/gemini-2.5-flash # This model is recommended for this purpose
  AI_MODEL_VISION: anthropic/claude-sonnet-4.6 # This model is recommended for this purpose
  AI_MODEL_NUTRITION: google/gemini-2.5-flash-lite # This model is recommended for this purpose
  AI_MODEL_ASSISTANT: anthropic/claude-sonnet-4.6 # Use whatever model you prefer
  AI_MODEL_ASSISTANT_LOW: google/gemini-2.5-flash # Use whatever model you prefer
  SCRAPFLY_API_KEY: "" # Can be provided to bypass CloudFlare anti-bot for better clip from URL support. Or, just use the browser extension instead since that grabs the HTML directly from the active webpage.

# === Please do not change any values below this line ===

services:
  proxy: # The proxy must not be removed. If needed, point your own proxy to this container, rather than removing this
    container_name: recipesage_proxy
    image: julianpoy/recipesage-selfhost-proxy:2026-08-16
    ports:
    - 7270:80
    depends_on:
      - static
      - api
      - pushpin
    restart: unless-stopped
  static: # Hosts frontend assets
    container_name: recipesage_static
    image: julianpoy/recipesage-selfhost:static-v4.0.3
    restart: unless-stopped
  api: # Hosts backend API
    container_name: recipesage_api
    image: julianpoy/recipesage-selfhost:api-v4.0.3
    depends_on:
      postgres:
        condition: service_healthy
      pushpin:
        condition: service_started
    command: ./scripts/selfhost-startup.sh
    environment:
      <<: *common-env
      # Please don't change these environment variables
      ENVIRONMENT: selfhost
      NODE_ENV: selfhost
      NODE_OPTIONS: "--max-old-space-size=400"
      MALLOC_ARENA_MAX: "2"
      FILESYSTEM_STORAGE_PATH: /rs-media
      STORAGE_TYPE: filesystem
      VERBOSE: "false"
      VERSION: selfhost
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_SSL: "false"
      POSTGRES_LOGGING: "false"
      DATABASE_SSL: "false"
      GRIP_URL: http://pushpin:5561/
      JOB_QUEUE_REDIS_HOST: valkey
      STRIPE_SK: "" # Value should not be set.
      GCM_KEYPAIR: "" # Value should not be set.
      SENTRY_DSN: "" # Value should not be set.
      STRIPE_WEBHOOK_SECRET: "" # Value should not be set
    volumes:
      - apimedia:/rs-media
    restart: unless-stopped
  pushpin: # Provides websocket support
    container_name: recipesage_pushpin
    image: julianpoy/pushpin:2023-09-17
    entrypoint: /bin/sh -c
    command:
      [
        'sed -i "s/sig_key=changeme/sig_key=$$GRIP_KEY/" /etc/pushpin/pushpin.conf && echo "* $${TARGET},over_http" > /etc/pushpin/routes && pushpin --merge-output',
      ]
    environment:
      <<: *common-env
      TARGET: api:3000
    restart: unless-stopped
  postgres: # Database
    container_name: recipesage_postgres
    image: postgres:16
    environment:
      <<: *common-env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "recipesage_selfhost", "-U", "recipesage_selfhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  valkey:
    restart: unless-stopped
    image: valkey/valkey

  # ===
  # Grocery Categorizer
  # A ML model that's quite resource intensive (and large) and requires AVX instruction support on your CPU. By default the selfhost stack uses the public API to categorize items.
  # If you decide to uncomment these lines, change the API container's GROCERY_CATEGORIZER_URL to http://grocery-categorizer:8000/
  # ===
  #
  # grocery-categorizer: # A server that runs a machine learning model able to categorize ingredient text for shopping list categorization.
  #   container_name: recipesage_grocery_categorizer
  #   image: julianpoy/grocery-categorizer:f9d9562
  #   restart: unless-stopped

volumes:
  apimedia:
    driver: local
  postgresdata:
    driver: local
